// +build !dev

package state

// Code generated by weld. DO NOT EDIT.

func MakeBackends() (Backends, error) {
	var (
		b backendsImpl
	)

	b.foo = foo()

	return &b, nil
}

type backendsImpl struct {
	foo bool
}

func (b *backendsImpl) Foo() bool {
	return b.foo
}
