package state

// Code generated by weld. DO NOT EDIT.

func MakeBackends() (Backends, error) {
	var (
		b backendsImpl
	)

	b.foo = MakeFoo()

	return &b, nil
}

type backendsImpl struct {
	foo Foo
}

func (b *backendsImpl) Foo() Foo {
	return b.foo
}
