// Code generated by "stringer -type=NodeType -trimprefix=NodeType"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeTypeUnknown-0]
	_ = x[NodeTypeSet-1]
	_ = x[NodeTypeFunc-2]
	_ = x[NodeTypeBind-3]
}

const _NodeType_name = "UnknownSetFuncBind"

var _NodeType_index = [...]uint8{0, 7, 10, 14, 18}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
